#+title:      Attenuation of Responses to Self-Generated Sounds in Auditory Cortical Neurons, Rummel and Sigurdsson 2016
#+date:       [2023-06-21 Wed 12:51]
#+filetags:   :bib:thesis:
#+identifier: 20230621T125118
#+reference:  attenuation_rummell_2016

The authors recorded auditory cortex activity from mice. They found that this activity was consistently attenuated in response to self generated sounds, both in pyramidal cells and interneurons.

They also found almost complete suppression of hippocampal activation in response to the same sounds.

They also found that there was an attenuation of auditory cortex activation caused by optogenetic activation of auditory thalamocortical connection - so completely bypassing the auditory tract - supporting the idea that this attenuation is a top-down, cortical, affair.

* abstract
To address this, we recorded the activity of neurons in the auditory cortex of mice in response to sounds generated by their own behavior. We found that the responses of auditory cortical neuronstothese self-generated sounds were consistently attenuated, compared with the same sounds generated independently of the animals’ behavior. This effect was observed in both putative pyramidal neurons and in interneurons and was stronger in lower layers of auditory cortex. Downstream of the auditory cortex, we found that responses of hippocampal neurons to self-generated sounds were almost entirely suppressed. Responses to selfgenerated optogenetic stimulation of auditory thalamocortical terminals were also attenuated, suggesting a cortical contribution to this effect. Further analyses revealed that the attenuation of self-generated sounds was not simply due to the nonspecific effects of movement or behavioral state on auditory responsiveness. However, the strength of attenuation depended on the degree to which self-generated sounds were expected to occur, in a cell-type-specific manner
