#+title:      Thesis ideas and thoughts
#+date:       [2023-04-09 Sun 10:29]
#+filetags:   :thesis:
#+identifier: 20230409T102947

Anything that has to do with my own thoughts and ideas about the project - ideas from analysis, their meaning, connecting stuff from literature, preparing for writing.

* What are we talking about?
- The difference in modulation of the auditory cortex between ipsi and contralateral hand playing.
- The (mechanism of the) effect of action on perception - on processing in fact.
    + The effect of action on the processing of the action's consequences
- Efference copies and how they work.
- Crosstalk between sensory and motor circuits
- Sensorimotor integration.
- how action affects/creates predictions/predictive coding: the modulation of the auditory cortex

Actually, a lot of the research in the lab, including my own?, is trying to tease apart the roles of prediction and motor action in their effect on processing and perception - is the effect of self-generated actions only due to predictive processing, or is there an additional effect?

* Why does it matter?
- can say something about the mechanism of [[id:20221208T101618.833052][Efference copy]] efferent copies (look at [cite:@buaronVoluntaryActionsModulate2020])  for language about efferent copies and the connection.
