#+title:      Thesis experiment planning
#+date:       [2023-04-09 Sun 09:37]
#+filetags:   :thesis:
#+identifier: 20230409T093744

* Design

**  Localizers:
    - Two localizers:
        + motor only
        + auditory only

    - One run each. (*question:* is it enough trials?)

**  Block design and timings
  - An 8 seconds fixation break between blocks for signal washout
  - 2 seconds instruction slide
  - 4 runs - divided by ear. 2 x LE, 2 x RE
  - 20 blocks each =  5 of each ear/hand combo, 10 ipsi 10 contra per run.
  - *357 sec (~6 minutes)* per experiment run
  - 8 runs, experiment run time (*total 2856 sec = 47.6 min*):

  - anatomical scan etc. (total 7.5 min):
      - localizer 0:25
      - spin echo field map: 0:49
      - T2 1:42
      - T1 4:26
  - *total time in scanner: 57 min* (without spare time for talking and rest between runs)

** Conditions
    - subjects will be playing the keyboard inside the MRI scanner
    - Blocks of RH-RE RH-LE LH-RE LH-LE
    - In each block participants will be asked to play twice in a row at their own pace
        + limited to 8 seconds

* Analysis
Basically, it's an exploratory analysis. We're looking for differences between hands in various ROis along the auditory pathway (thalamus, olivary nucleus, A1/2 etc.). We'll continue based on the results that we have.

We'll talk about the functional connectivity analysis after we have the data and some functional analyses done. We don't need to change the experiment to support it.

We need a lot of coverage in the scan (a lot of slices) so we'll have data from subcortical parts as well.

How about the cerebellum?

We can consider DTI based on the length of the pilot - we don't have anyone to analyse it at the moment anyways.

*** GLM
- Compare the activation in the auditory cortex between ipsi and contra hand playing. Separately for each ear
    - RH-LE > RH-RE
    - LH-RE > LH-LE

*** MVPA
    - Decode hand from auditory cortex.
        + once decoding from the stimulated ear (cortex)
        + once decoding from the unstimulated ear.
    - cross-decoding: train on stimulated ear, test on oposite ear
    - we can't "cross decode" betewen hemispheres because the order of the voxels in the neighborhood matters (it's the order of the features in the vector the classifier learns) and the homology betewen the L and R hemispheres is no where near exact enough.

*** functional connectivity (PPI?)
    - Compare (task) functional connectivity between ipsi and contra hands per ear.
        + *question*: of course there will be a correlation in activity between motor and auditory cortex, because the both operate at the timing of key presses - how to deal with this?



* Special notes

* check list preliminary talk
1. Thank you
2. Metal form
3. ID photocopy
4. Explain experiment
5. Explain the task
6. Ask about movies

* check list experiment
1. Set control box input settings
2. Set computer volume to max
3. Adjust MRI volume
4. Set computer to extend screens
5. Sound check (before entering the bore)
6. Keyboard check
7. Explain instructions again
8. 2x motor localizer
9. 2x auditory localizer
10. Put on a movie, scan FLAIR
11. Explain the task again
12. Verify which ear to start on
13. 4x experimental run
