#+title:      straddle (options)
#+date:       [2023-04-06 Thu 10:18]
#+filetags:   :finance:
#+identifier: 20230406T101834

אסטרטגיית אוכף. אסטרטגיית קניית [[denote:20230331T071217][אופציות ונילה]] בה קונים (או מוכרים) גם אופציות put וגם call על אותו נכס באותו מחיר מימוש (strike price) ואותו תאריך פקיעה.

* long straddle
לינק: https://www.investopedia.com/terms/l/longstraddle.asp

זו אסטרטגיה טובה כשמאמינים שהמחיר של המניה (או השוק בכללותו) מאוד volatile, תנודתיים, כלומר המחיר של המניה צפוי להשתנות הרבה ובצורה חדה, אבל לא בטוחים באיזה כיוון.
למשל - לפני שחרור דוחות רבעוניים של החברה, או הודעות משמעותיות, כשלא בטוחים לאיזה כיוון ההודעה תשפיע על המניה.
זו אסטרטגיה שבה מהמרים על (או משקיעים ב-) עצם התנודתיות של השוק ולא בערך של המניה עצמו.

כדי להיות רווחיים צריך שהרווח מהכיוון שבו מחיר המניה השתנה בפועל יהיה גדול יותר מסה"כ הפרמיה ששילמנו על שני הכיוונים גם יחד.
כדי להבין בכמה המניה צריכה לעלות או לרדת כדי לעשות רווח מהאוכף צריך לחלק את סכום הפרמיות של ה put וה call במחיר המימוש - זה אחוז שינוי המחיר של המניה בשביל להיות break even.
אם מחיר המניה נשאר קבוע יחסית, נפסיד את מחיר שתי הפרמיות ששילמנו.

התנודה שהשוק "צופה" במחיר המניה מגולמת בפרמיה - אם נוסיף ונחסיר את סכום הפרמיות ממחיר המניה, אפשר להגיד שהשוק מצפה שמחיר המניה ינוע בטווח הזה.
למשל, אם מחיר המניה הוא 55$ והפרמיה לפני הכיוונים היא 2.5$, אז אפשר לומר שהשוק מצפה מהמניה לנוע בין 50$-60$ בטווח הזמן של האופציה. דרך נוספת להבין את פוטנציאל הרווח וההפסד של האוכף הוא כזה: האוכף יהיה רווחי אם המניה תחרוג מהטווח שהשוק מצפה ממנה להיות בו.

זה לא כל כך פשוט מכיוון שמוכרי האופציות מודעים גם הם לאירועים החדשותיים שהשוק מצפה להם, והם מעלים את מחיר הפרמיות כדי לגלם אחוז מסוים של השינוי הצפוי - לכן, על מנת להרוויח מאוכף השוק צריך לעשות תנועה משמעותית במיוחד.

* short straddle

אסטרטגיה הפוכה, בה מהמרים על _חוסר התנודתיות_ של השוק: במקום לקנות call ו put, מוכרים אותם, ומקווים שהאופציה תפקע כשמחיר המניה נשאר כל הזמן בערך במחיר המימוש, או המחיר שהיה למניה בזמן שהאופציות נכתבו.
