#+title:      Microdosing journal
#+date:       [2023-05-23 Tue 16:22]
#+filetags:   :journal:
#+identifier: 20230523T162209

* 17.5 יום רביעי, 0.05 ג', 7 בבוקר
לא הרגשתי (כמעט) שום אפקט, אני חושב שאולי הייתי קצת יותר זורם וקצת יותר פתוח, אבל באמת ברמה שאני לא בטוח אם דמיינתי או לא

* 18.5 יום חמישי, 0.1 ג', 7:45 בבוקר
8:00 - כבר חושב שאני מרגיש השפעה, לקחתי אותן עם כוס תה קלוי, בדיעבד אולי טעות, כי בכל זאת יש בזה קפאין. להבא מעדיף לקחת עם תה צמחים ולרווח מהקפאין.
נמנמתי עם אביגיל בשנת הבוקר שלה והרגשתי את המחשבות שלי נודדות בצורה נעימה וחדשה, עם יותר התבוננות שלי, ולכיוונים חדשים, יותר רגשיים.

* 19.5 יום שישי, 0.15 גר'
בקושי הרגשתי משהו כל היום, אולי קצת עייפות, ואת התחושה הזאת שמחפתיע לגלות שבעצם יום שישי, כי ממש לא הייתה לי את ההרגשה שזה ככה.

* 21.5 יום ראשון, 0.2 גר', 11:00, אחרי אוכל וקצת קפה
נראה לי שאני מרגיש את הגוף שלי יותר
היה לי יותר קל להתחבר אל אביגיל כשהאילת יצאה איתה מהבית
מונולוג פנימי קצת מהיר יותר (מדי), יותר נחווה כמונולוג
תפעולות קצת מהירות יותר (מדי)
ליבידו אפילו יותר גבוה מבד"כ (:
בסהכ השפעה עדינה מאוד עד בלתי מורגשת במהלך היום

* 23.5, יום שלישי, 0.25 גר', 6:00,
קצת יותר קלות
קצת עייפות בשעה שאחרי שלקחתי, אבל זה יכול להיות גם בגלל שזה בוקר
ב 9, אחרי קצת הוג'יצ'ה עם קפאין התחלתי להרגיש שינוי יותר מובחן בתודעה - בזמן שסידרתי ירקות לתנור הרגשתי שאני יכול ורוצה להאט, לתת תשומת לב והערכה לירקות, התבוננתי הרבה זמן בסלק, הערכתי את הגוונים השונים, את הצורה שלו, התבנית של הכתמים, הריח המתוק אדמתי, ואז באופן דומה עם הגזר ועם הבטטה. זה הרגיש נעים.
היום ממשיך, עדיין מרגיש את האפקט באיזשהו אופן
מתודלק בעוד תה, מרגיש את האפקט של הקפאין
המחשבות קצת נודדות
חושב על שקד, יש עצבות וכמיהה לחיים אחרים
המשך היום, קצת מבולבל, עייף, כנראה כי אכלתי בשר בצהריים, מחפש הסחות דעת
מתלבט אם הגיוני לדחוף את המינון עוד קצת, עד שבאמת ארגיש intoxicated ורק אז לרדת. אולי זה פשוט לא מגיע לאותן תחושות שהיו לי על אסיד. זה בכל מקרה באמת שונה ויותר רך, שזה נחמד.
