#+title:      How Movement Modulates Hearing, Schneider & Mooney
#+date:       [2023-05-11 Thu 13:58]
#+filetags:   :bib:review:thesis:
#+identifier: 20230511T135849
#+reference:  schneiderHowMovementModulates2018

* reading notes
A possible role of motor auditory modulation are the reallocation of neural resources from processing information sources which are less reliable during movement (=auditory) to other modalities, like vision.

Since the auditory consequences of our actions are so varied, the canceling-type modulation of the auditory system must be very adaptive.

the auditory cortex receives a wide array of nonauditory afferents, including top-down inputs from frontal cortical regions important to motor planning and bottom-up inputs from neuromodulatory cell groups that facilitate experience-dependent auditory cortical plasticity.

There is evidence that the auditory cortex is the region where self-generated other-generated vocalizations.
The suppression of activation in the auditory cortex is heterogeneous - some areas show extensive suppression while others not so much. This implies that the source of the suppressing signal is cortical, rather than a general filter applied somewhere in the periphery.
From electrophysiological recordings it seems that the areas being suppressed are the non-core areas - the belt and the parabelt, and that A1 responds relatively the same for self- vs other-generated vocalizations.

(Vocalization) We know that the modulation of the auditory cortex is predictive, i.e. the modulation is targeting a specific, predicted auditory consequence, because when we change the sound characteristics of the produced vocalization the auditory cortex is excited instead of suppressed (marmosets), or suppressed to a lesser degree (humans).
The specific attributes of the auditory consequence which is predicted based on motor action are the ones being suppressed through modulation. In humans, the suppression of vocalizations targets the sound of the average utterance of a given word - the more different the utterance is from the average, the less its processing will be affected.

More highlights in the paper file
