#+title:      Voluntary Actions Modulate Perception, Buaron et al.
#+date:       [2023-04-03 Mon 12:23]
#+filetags:   :bib:thesis:
#+identifier: 20230403T122319
#+reference:  buaronVoluntaryActionsModulate2020b

This paper investigates how voluntary actions affect sensory modulations in the visual domain.
The study found that there was significant modulation of perceived brightness in self-generated vs externally-generated (identical) stimuli, and that the pattern of behavioral and neural modulations is such that the modulation is stronger in the visual cortex contralateral to the hand triggering the stimulus (so ipsilateral visual and motor cortices).

In addition the study found that fMRI responses in visual cortices differentiated between stimuli triggered by right/left hand. This suggests that the visual cortex contains the information regarding the active hand, and this information is assumed to arrive there through the mechanism of an [[denote:20230402T112858][Efference copy]].

* reading notes
*** The experimental procedure
The experimental procedure involved presenting identical visual stimuli to participants that were either self-triggered (using right/left hand button presses) or triggered by the computer. The participants were asked to judge the relative brightness of the stimuli presented in either the right or left visual field.
The study also used a visual localizer task to functionally define the visual cortex. The researchers used GLM with a contrast of right visual field > left visual field to define regions sensitive to visual stimulation in either right or left visual fields.

they measured the perceptual modulation like this: Modulation index = |%active brighter − 50%|. This measures the proportion of *trials* where the self-generated stimulus was judged as brighter, not the degree, or how much brighter it seemed.
*** results
They found stronger perceptual modulation for self-generated stimuli but not in a specific direciton - some subjects saw it brighter, some darker
They found a difference between lateral configurations: they were able to decode the hand from the visual cortex - this means that the activation there was affected differently depending on the active hand.
