#+title:      Analysis log
#+date:       [2023-04-14 Fri 18:34]

* log
*** 28.5
First entry.
Currently 5 (4.5) viable subjects.
103 still waiting for a re-scan of the anatomy, delayed on account of new earring
102 excluded for left-handedness, 107 for too many errors.

Noticed that 2nd level averages are displayed on the MNI brain but couldn't figure out why it's not in the original space.

Still need to create the 3rd level template.

Tried to run the analysis for 103 regardless of cropped anatomical scan. Forgot to remove the first scan's EV from raw/behavioral. Re-ran it. Need to verify it didn't fail and run 2nd level as well.
*** 29.5
Ran 2nd level on inbal's data (sub 103), as the 1st level looked alright re registration.
Ran 3rd level (woohoo!) Using subjects 101, 104, 105, 106 - so without inbal for now, waiting on the results to show roy.
Used https://www.youtube.com/watch?v=nyajZKJ-uwk&list=PLB2iAtgpI4YHlH4sno3i3CUjCofI38a-3&index=16 as instructions.
Talked to roy and shahar, we said that the results are consistent with the findings on same-hemisphere modulation being stronger than the contralateral case. I said it looks to me like the modulation doesn't seem to related much to the stimulated ear at all. We saw significant activation in the unstimulated auditory cortex.

Talked with roy about third level analysis, said it's compatible with reznik in terms of ispilateral enhancement of activity ([cite:@reznikEnhancedAuditoryEvoked2015], [cite:@reznikLateralizedEnhancementAuditory2014])
we saw significant activation in the "unstimulated" auditory cortex.
He wants to do an active vs. Passive contrast even though they're in different runs. Need to figure out how to do this.
Currently re-running 101's motor-onl (for 5 copes).

TDOO:
run 101's motor-only 2nd level
run motor-only 3rd level.

*** 31.5
Looking at motor only results, pretty clear that the left hand activates a much wider area of the cortex - probably because when you're an expert (all subs are R handed) you activate the required areas more specifically.

TODO: read papers by bob zattore

*** 2.6
After running looking at the motor only and auditory only, it's pretty clear that the audiomotor condition, at this time and using GLM, doesn't differentially activate the auditory cortex

* scripts, file names and code snippets
- for displaying all 1st level or 2nd level GLM for a subject, using fsleyes:
    - checkFirstLevel.py
    - checkSecondLevel.py
- for creating the 3rd level analysis in FSL:
        for CN in `seq 5`; do echo ""; echo ; "cope$CN"; echo "--------"; ls /media/user/Data/fmri-data/analysis-output/10[1456]/functional/*motorLoc_mean.gfeat/cope$CN.feat/stats/cope1.nii.gz; done
        then paste each block into FSL
- cope numbers meaning in 2nd level .gfeat dirs:
    - In the outer level (which comes from the 1st level analysis, each is a directory):
            Cope1: R>L
            Cope2: L>R
            Cope3: R>rest
            Cope4: L>rest
            Cope5: L+R>rest (the given ear auditory, while motor action is performed)
    - in the inner level:
            Cope1 is the mean image itself.
            So 101_audiomotor_LE_mean.gfeat/cope2.feat/stats/cope1.nii.gz
            is the mean image of L>R contrast in the LE of subject 10   1

* prompts for chatgpt etc.:
- Summarizing and Analysis:
  "Summarize the main arguments in this article/abstract:"
  "Analyze the strengths and weaknesses of this methodology:"
  "Compare and contrast [theory A] and [theory B] in the context of [field]:"
  "Identify the key findings and implications of this research paper:"
  "Describe the theoretical framework of this study and how it relates to the findings:"

- Research Questions and Gaps:
  "List potential research questions related to [topic]:"
  "Identify gaps in the literature on [topic]:"
  "Generate a list of research hypotheses related to [topic]:"
  "Identify potential areas for future research in the context of this article/abstract:"
  "Suggest novel applications of [theory/concept] within [field]:"

- Methodology and Techniques:
  "What are the limitations of using [statistical method] in [research context]?"
  "Create a recipie for the methods used in this [paper/thesis]"
  "Suggest interdisciplinary approaches to [research question/problem]:"
  "Explain how [qualitative/quantitative] research methods can be used to address [research question]:"
  "Describe the advantages of using a mixed-methods approach for studying [topic]:"
  "Recommend best practices for data collection and analysis in [field/research context]:"

